plugins:
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"
yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
  "@parcel/workers@2.5.0":
    dependencies:
      "@parcel/core": "2.5.0"
  "parcel-namer-rewrite@2.0.0-rc.2":
    dependencies:
      "@parcel/utils": "2.5.0"
  "@parcel/package-manager@2.5.0":
    dependencies:
      "@parcel/namer-default": "2.5.0"
