plugins:
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"
yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
  "@parcel/workers@2.4.1":
    dependencies:
      "@parcel/core": "2.4.1"
  "@parcel/fs@2.4.1":
    dependencies:
      "@parcel/core": "2.4.1"
  "@parcel/cache@2.4.1":
    dependencies:
      "@parcel/core": "2.4.1"
  "@parcel/package-manager@2.4.1":
    dependencies:
      "@parcel/core": "2.4.1"
