[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
handlebars = { version = "4.2.2", features = ["rust-embed"] }
serde_json = "1.0.79"
poem = { version = "1.3.58", features = ["static-files"] }
rust-embed = "6.4.0"
