name: check
on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # tag=v17
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - uses: cachix/cachix-action@73e75d1a0cd4330597a571e8f9dedb41faa2fc4e # tag=v10
        with:
          name: andre-krueger
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
